from django.urls import path
from .views import (
    LandingView,
    SignupView,
    LoginView,
    LogoutView,
    GitHubAppCallbackView,
    UserDashboardView,
    LogsStreamView,
    LogDetailView,
    CreateStripeCheckoutSessionView,
    StripeWebhookListenerView,
    UsageMeteringWebhookView,
    CLIEngineTriggerGatewayView,
    CLIAuthTokenView,
    CLIAuthExchangeView,
    APIKeyDashboardListView,
    GenerateNewAPIKeyView,
    RevokeAPIKeyView,
    DeploymentListView,
    DeploymentDetailView,
    TriggerDeploymentView,
    AdminDashboardView,
    AdminToggleUserActiveView,
    AdminDeleteUserView,
    PRDashboardView,
    DeploymentDashboardView,
    GitHubIntegrationDashboardView,
    BillingDashboardView,
    BillingRecordIngestionView,
    BillingSpendSummaryView,
    BillingPredictionListView,
    BillingAlertListView,
    BillingAlertAcknowledgeView,
)

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/github/callback/', GitHubAppCallbackView.as_view(), name='github_callback'),
    path('dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('dashboard/admin/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('dashboard/admin/users/toggle-active/', AdminToggleUserActiveView.as_view(), name='admin_toggle_user'),
    path('dashboard/admin/users/delete/', AdminDeleteUserView.as_view(), name='admin_delete_user'),
    path('dashboard/prs/', PRDashboardView.as_view(), name='pr_dashboard'),
    path('dashboard/deployments/', DeploymentDashboardView.as_view(), name='deploy_dashboard'),
    path('dashboard/github/', GitHubIntegrationDashboardView.as_view(), name='github_dashboard'),
    path('api/v1/logs-stream/', LogsStreamView.as_view(), name='logs_stream'),
    path('billing/create-checkout-session/', CreateStripeCheckoutSessionView.as_view(), name='stripe_checkout'),
    path('api/v1/billing/stripe-webhook/', StripeWebhookListenerView.as_view(), name='stripe_webhook_ingress'),
    path('api/v1/meter-event/', UsageMeteringWebhookView.as_view(), name='internal_telemetry_meter'),
    path('api/v1/cli/trigger-fix', CLIEngineTriggerGatewayView.as_view(), name='cli_gateway_endpoint'),
    path('api/v1/cli/auth/token', CLIAuthTokenView.as_view(), name='cli_auth_token'),
    path('api/v1/cli/auth/exchange', CLIAuthExchangeView.as_view(), name='cli_auth_exchange'),
    path('dashboard/developer-tokens/', APIKeyDashboardListView.as_view(), name='api_key_dashboard'),
    path('dashboard/developer-tokens/generate/', GenerateNewAPIKeyView.as_view(), name='generate_key'),
    path('dashboard/developer-tokens/revoke/<int:key_id>/', RevokeAPIKeyView.as_view(), name='revoke_key'),
    path('api/v1/deployments/', DeploymentListView.as_view(), name='deployment_list'),
    path('api/v1/deployments/<int:deployment_id>/', DeploymentDetailView.as_view(), name='deployment_detail'),
    path('api/v1/deployments/trigger/', TriggerDeploymentView.as_view(), name='trigger_deployment'),
    path('logs/<str:project_id>/', LogDetailView.as_view(), name='log_detail'),
    path('dashboard/cost-intelligence/', BillingDashboardView.as_view(), name='cost_intelligence'),
    path('api/v1/billing/ingest/', BillingRecordIngestionView.as_view(), name='billing_ingest'),
    path('api/v1/billing/summary/', BillingSpendSummaryView.as_view(), name='billing_summary'),
    path('api/v1/billing/predictions/', BillingPredictionListView.as_view(), name='billing_predictions'),
    path('api/v1/billing/alerts/', BillingAlertListView.as_view(), name='billing_alerts'),
    path('api/v1/billing/alerts/<int:alert_id>/acknowledge/', BillingAlertAcknowledgeView.as_view(), name='billing_alert_acknowledge'),
]
