# Generated by Django 6.0.6 on 2026-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_enterprise_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(db_index=True, max_length=255)),
                ('installation_id', models.CharField(max_length=100)),
                ('session_token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
