# Generated by Django 6.0.6 on 2026-06-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_clisession'),
        ('dashboard', '0012_billing_models'),
    ]

    operations = [
    ]
